# 3.1 浮點數的世界
在AI的世界所有的資料都會使用編碼轉換成浮點數並進行訓練分析
輸入資料>編碼>神經元(模型參數)>解碼>輸出結果
神經網路會透過逐層學習的方式,將一種形式的資料轉換成另一種形式的資料
- 前段神經層:

    物體邊緣檢測or紋理偵測(皮膚,輪廓)
- 後端神經層:

    捕捉更複雜的結構(器官,眼睛,耳朵)
## 資料前置處理
純量->向量->矩陣->陣列->陳列

Python串列:散佈的記憶體規劃

Python張量:整區記憶體規劃
## 張量 多維陣列


In [74]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [75]:
a[1]

tensor(1.)

In [76]:
print(float(a[0]))
a[2] = 2
a

1.0


tensor([1., 1., 2.])

In [77]:

points = torch.Tensor([4,1,5,3,2,1])
points
points.shape
points.reshape([2,3])

tensor([[4., 1., 5.],
        [3., 2., 1.]])

In [78]:
points = torch.Tensor([[4,1,5],[3,2,1]])
points[0]
points[:,1:2]


tensor([[1.],
        [2.]])

# 利用索引值操作張量

In [79]:

img_t=torch.randn(3,5,5)
batch_t = torch.randn(2,3,5,5)
img_named = img_t.refine_names(..., 'channels', 'rows', 'cols')
batch_named = batch_t.refine_names(...,'out_channel', 'rows', 'cols')
print(img_named.names,batch_named.names)

('channels', 'rows', 'cols') (None, 'out_channel', 'rows', 'cols')
